use_cuda: true

paths:
  data_dir: "data"
  images_dir: "data/Images"
  captions_json: "data/captions.json"
  experiments_dir: "experiments"
  checkpoints_dir: "experiments/checkpoints"
  results_dir: "experiments/results"

data:
  min_freq: 1

model:
  attention_dim: 512
  embed_dim: 512
  decoder_dim: 512
  max_len: 30
  dropout: 0.4
  encoder_trainable: false

training:
  batch_size: 64
  lr: 5e-4
  epochs: 50
  grad_clip: 5.0
  print_every: 50
  attn_reg_lambda: 1.0
